version: 2.1
jobs:  
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout 
      - setup_remote_docker     
      - run:
          name: Build
          command: |
            DOCKER_PATH="thanhlam00290/docker-webdav"
            docker --version
            docker build -t $DOCKER_PATH .
            docker login -p ${DOCKER_PASSWORD} -u ${DOCKER_USERNAME}
            docker push $DOCKER_PATH
            docker tag $DOCKER_PATH $DOCKER_PATH:0.0.${CIRCLE_BUILD_NUM}
            docker push $DOCKER_PATH:0.0.${CIRCLE_BUILD_NUM}
            docker tag $DOCKER_PATH $DOCKER_PATH:latest
            docker push $DOCKER_PATH:latest
  

  
workflows:
  default:
    jobs:
      - build      